# Name of the workflow
name: Generate Release Log

# Run on every commit tag which begins with "v" (e.g., "v0.1.4")
on:
  workflow_run:
    workflows: ["Version Increment Workflow"]
    types:
      - completed

# Automatically create a GitHub Release, with release details specified (the relevant commits)
jobs:
  release-logs:
    name: "Release"
    runs-on: "ubuntu-latest"
    steps:
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
        with:
         path: ./package.json
    
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ steps.package-version.outputs.current-version}}"
          prerelease: false
