# Name of the workflow
name: Generate Release Log

# Run on every commit tag which begins with "v" (e.g., "v0.1.4")
on:
  workflow_run:
    workflows: ["Version Increment Workflow"]
    types:
      - completed

# Automatically create a GitHub Release, with release details specified (the relevant commits)
jobs:
  release-logs:
    name: "Release"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Build & test"
        run: |
          echo "${{ JSON.stringyfy(github) }}"
    
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
