name: Version Increment Workflow

on:
  push:
    branches:
      - main

jobs:
  version-increment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci
      
      - name: Version Increment Action
        uses: BTARPAR/custom-action@v4.0.0
        with:
          github-token: ${{ secrets.GTOKEN }}
