name: Version Increment Workflow

on:
  push:
    branches:
      - main

jobs:
  version-increment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Version Increment Action
        uses: BTARPAR/custom-action@v2.0.0
        with:
          github-token: ${{ secrets.GTOKEN }}
